code:
  secret: ${random.value}
  bignumber: ${random.long}
  uuid: ${random.uuid}

server:
  port: 1234

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost/spring
#    url: jdbc:mysql://localhost/spring?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: koreait